### ISSUE TITLE
bugs when infer

### ISSUE THREAD

**Issue by cuge1995** [yifanlu0227/CoAlign#12]
```
CoAlign/opencood/utils/common_utils.py", line 217, in <listcomp>
    iou = [box.intersection(b).area / (box.union(b).area) for b in boxes]
ZeroDivisionError: float division by zero
```

**Comment by yifanlu0227** [comment]
Please provide more information about this bug.

- Which model and which yaml file?
- Inference command?

**Comment by cuge1995** [comment]
python opencood/tools/inference.py --model_dir /home/selfdriving/mingchao/CoAlign/opencood/logs/dairv2x_point_pillar_lidar_early_2023_08_18_16_31_19/ --fusion_method intermediate

**Comment by yifanlu0227** [comment]
Could you try to infer my experiment log?

https://drive.google.com/drive/folders/1J7JTMzVY30Rtj6z8uKal3gzQd-kN67xz?usp=drive_link

**Comment by cuge1995** [comment]
The same bug
```
Traceback (most recent call last):
  File "opencood/tools/inference.py", line 230, in <module>
    main()
  File "opencood/tools/inference.py", line 169, in main
    0.3)
  File "/home/selfdriving/mingchao/CoAlign/opencood/utils/eval_utils.py", line 77, in caluclate_tp_fp
    ious = common_utils.compute_iou(det_polygon, gt_polygon_list)
  File "/home/selfdriving/mingchao/CoAlign/opencood/utils/common_utils.py", line 217, in compute_iou
    iou = [box.intersection(b).area / (box.union(b).area) for b in boxes]
  File "/home/selfdriving/mingchao/CoAlign/opencood/utils/common_utils.py", line 217, in <listcomp>
    iou = [box.intersection(b).area / (box.union(b).area) for b in boxes]
ZeroDivisionError: float division by zero
```

**Comment by yifanlu0227** [comment]
This may be caused by an error in the annotation file. Maybe you can download again and try again.

**Comment by yifanlu0227** [comment]
This issue will be closed due to no new comments.
