### ISSUE TITLE
Bugs with multiple GPUs training with DDP

### ISSUE THREAD

**Issue by rwang5203** [yifanlu0227/CoAlign#18]
Hi, I tried using the train_ddp.py to leverage multiple GPUs for faster training. Everything started fine, but when I was finishing the last epoch of the training process, an error showed and the training process was terminated.
This is the error message:
```
[E ProcessGroupNCCL.cpp:587] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800936 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:587] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(OpType=BROADCAST, Timeout(ms)=1800000) ran for 1801044 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:587] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(OpType=BROADCAST, Timeout(ms)=1800000) ran for 1801058 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:341] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:341] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:341] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2003339 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 2 (pid: 2003341) of binary: /home//.conda/envs/coalign/bin/python
Traceback (most recent call last):
  File "/home//.conda/envs/coalign/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home//.conda/envs/coalign/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main    launch(args)
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home//.conda/envs/coalign/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
========================================================
opencood/tools/train_ddp.py FAILED
--------------------------------------------------------
Failures:
[1]:
  time      : 2023-10-25_20:08:24
  host      : lthpc-AS-4124GS-TNR
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 2003342)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2003342
[2]:
  time      : 2023-10-25_20:08:24
  host      : lthpc-AS-4124GS-TNR
  rank      : 4 (local_rank: 4)
  exitcode  : -6 (pid: 2003343)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2003343
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-25_20:08:24
  host      : lthpc-AS-4124GS-TNR
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 2003341)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2003341
========================================================
```
What could possibily be the issue here? Thanks!

**Comment by yifanlu0227** [comment]
I encounter this bug on some machines, but not on others. I am not quite sure about the specific reasons behind this issue, sorry.

**Comment by yifanlu0227** [comment]
#23
