### ISSUE TITLE
ValueError: '6853' is not in list

### ISSUE THREAD

**Issue by huanghelouzi** [yifanlu0227/CoAlign#21]
Hi, after spending an afternoon installing unfriendly dependencies from the source code, the following problem occurred. Can you help me see what the reason is? Thanks.

ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/xxx/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/xxx/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/xxx/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/xxx/data/opencood/CoAlign-main/opencood/data_utils/datasets/intermediate_fusion_dataset.py", line 312, in __getitem__
    cur_agent_in_all_agent = [all_agent_id_list.index(cur_agent) for cur_agent in cur_agent_id_list] # indexing current agent in `all_agent_id_list`
  File "/data/xxx/data/opencood/CoAlign-main/opencood/data_utils/datasets/intermediate_fusion_dataset.py", line 312, in <listcomp>
    cur_agent_in_all_agent = [all_agent_id_list.index(cur_agent) for cur_agent in cur_agent_id_list] # indexing current agent in `all_agent_id_list`
ValueError: '6853' is not in list

**Comment by yifanlu0227** [comment]
The dependency installation is indeed intractable, sorry for that.

Let's address this problem. You use the `prec_calc` and checkpoints from Google Drive right? What's the running command?

**Comment by huanghelouzi** [comment]
I trained from scratch, and the following command was executed.
```shell
python /data/xxx/data/opencood/CoAlign-main/open
cood/tools/train.py -y /data/xxx/data/opencood/CoAlign-main/opencood/hypes_yaml/opv2v/lidar_only_with_noise/coalign/pointpillar_coalign.yaml
```

`stage1_ boxes.json` and other two files are downloaded from your Google drive, while the opv2v dataset is downloaded from opencood.

**Comment by huanghelouzi** [comment]
This is all output of model, hoping to be helpful to you. It should be noted that sometimes only one batch is executed, and sometimes there are only a few.
```
Dataset Building
Dataset dir: /data/xxx/data/opencood/OpenCOOD-main/opv2v_data_dumping/train
too many cavs reinitialize
Dataset dir: /data/x/data/opencood/OpenCOOD-main/opv2v_data_dumping/validate
too many cavs reinitialize
too many cavs reinitialize
Creating Model
Training start
learning rate 0.002000
/data/x/data/opencood/CoAlign-main/opencood/models/sub_modules/box_align_v2.py:96: RuntimeWarning: invalid value encountered in sqrt
  - TwoAB
/data/x/data/opencood/CoAlign-main/opencood/models/sub_modules/box_align_v2.py:96: RuntimeWarning: invalid value encountered in sqrt
  - TwoAB
/data/x/data/opencood/CoAlign-main/opencood/models/sub_modules/box_align_v2.py:96: RuntimeWarning: invalid value encountered in sqrt
  - TwoAB
/data/x/data/opencood/CoAlign-main/opencood/models/sub_modules/box_align_v2.py:96: RuntimeWarning: invalid value encountered in sqrt
  - TwoAB
[epoch 0][1/1691] || Loss: 993.9803 || Conf Loss: 992.0069 || Loc Loss: 1.8459 || Dir Loss: 0.1275 || IoU Loss: 0.0000
Traceback (most recent call last):
  File "train.py", line 197, in <module>
    main()
  File "train.py", line 105, in main
    for i, batch_data in enumerate(train_loader):
  File "/data/x/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/data/x/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/data/x/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/data/x/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/data/x/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/x/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/x/miniconda3/envs/coalign/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/x/data/opencood/CoAlign-main/opencood/data_utils/datasets/intermediate_fusion_dataset.py", line 312, in __getitem__
    cur_agent_in_all_agent = [all_agent_id_list.index(cur_agent) for cur_agent in cur_agent_id_list] # indexing current agent in `all_agent_id_list`
  File "/data/x/data/opencood/CoAlign-main/opencood/data_utils/datasets/intermediate_fusion_dataset.py", line 312, in <listcomp>
    cur_agent_in_all_agent = [all_agent_id_list.index(cur_agent) for cur_agent in cur_agent_id_list] # indexing current agent in `all_agent_id_list`
ValueError: '1260' is not in list
```

**Comment by yifanlu0227** [comment]
Thanks! I got it. 

By the way, could you please infer the [OPV2V experiment log](https://drive.google.com/drive/folders/14VdGUZ26j4NF0UG_XuNsU7E0uGh_DmOU?usp=sharing
) from Google Drive?

As illustrated in [CoAlign Installation Guide](https://udtkdfu8mk.feishu.cn/docx/LlMpdu3pNoCS94xxhjMcOWIynie), when training the intemediate fusion part, I use  `opencood/hypes_yaml/opv2v/lidar_only_with_noise/coalign/pointpillar_coalign_woba.yaml `. It does not involves the box alignment. 

I will continue to look at the cause of this bug.

**Comment by huanghelouzi** [comment]
I know the reason for the error, yaml should have chosen woba.yaml, although I haven't really understood the difference between these. Thanks.

**Comment by yifanlu0227** [comment]
pointpillar_coalign.yaml  includes an extra entity 'box_align' as follows:
```
box_align:
  train_result: "opencood/logs/coalign_precalc/opv2v/train/stage1_boxes.json"
  val_result: "opencood/logs/coalign_precalc/opv2v/val/stage1_boxes.json"
  test_result: "opencood/logs/coalign_precalc/opv2v/test/stage1_boxes.json"
  args:
    use_uncertainty: true
    landmark_SE2: true
    adaptive_landmark: false
    normalize_uncertainty: false
    abandon_hard_cases: true
    drop_hard_boxes: true
```

This will enable the box alignment to correct pose errors. 

However, during the training, I remove this entity to let the model see various noise in pose. It will increase the robustness of the model.

**Comment by huanghelouzi** [comment]
Thank you very much, I think that I need to debug the code of Coalign to understand your paper.
